version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "dg/cicd/dockerhub:username"
    DOCKERHUB_PASSWORD: "dg/cicd/dockerhub:password"

phases:
  install:
    commands:
      - echo "$DOCKERHUB_USERNAME"
      - echo "Installing Docker Compose"
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - export COMMIT_HASH=$(CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo $COMMIT_HASH
  build:
    commands:
      - echo "Building Docker image"
      - docker-compose build
  post_build:
    commands:
      - echo "Tagging Docker images"
      - docker tag service-01:latest "$DOCKERHUB_USERNAME/dg-service-01:$COMMIT_HASH"
      - echo "Pushing Docker images to Docker Hub"
      - docker push "$DOCKERHUB_USERNAME/dg-service-01:$COMMIT_HASH"
