version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d5n5m2p7
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t myapp:latest .

  post_build:
     commands:
      - echo Pusing the Docker image...
      - docker tag myapp:latest public.ecr.aws/d5n5m2p7/my-app-docker-test-ecr:latest
      - docker push public.ecr.aws/d5n5m2p7/my-app-docker-test-ecr:latest
# artifacts:
#   files: imagedefinitions.json
